# Use root/example as user/password credentials
version: '3.9'

services:
  whisper:
    image: whisper:latest
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/arm64
    # runtime: nvidia
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - PYTORCH_ENABLE_MPS_FALLBACK=1
      - USE_GPU=1
    volumes:
      - whisper_data:/app/src/uploads


volumes:
  whisper_data: {}
